#!/usr/bin/env ruby

# Load local development directories, if it looks like we are in a repository
DIRNAME = File.dirname(__FILE__);
if File.exists?("#{DIRNAME}/../lib/movewin.rb") &&
   File.directory?("#{DIRNAME}/../ext/movewin")
then
  $LOAD_PATH.unshift("#{DIRNAME}/../lib", "#{DIRNAME}/../ext")
else
  require 'rubygems'
end

require 'movewin'

ME = File.basename($0)
def die(*msg); abort "#{ME}: #{msg}"; end
unless MoveWin.recording_authorized?
  die 'not authorized to do screen recording'
end
unless MoveWin.accessibility_authorized?
  die 'not authorized to use accessibility API'
end

pattern = ARGV.first
windows = MoveWin.windows
if pattern
  window = windows.detect { |w| "#{w.app_name} #{w.title}".match(pattern) }
else
  window = windows.first
end
die "no window found#{pattern ? ' matching pattern' : ''}" unless window

delay = 0.05
while true
  x, y = window.position
  window.move!(x + 1, y)
  sleep delay
  window.move!(x, y)
  sleep delay
end
